"""add recurring todo occurrences

Revision ID: 0dd8dae16435
Revises: d2e5f8a1b4c7
Create Date: 2026-09-02 11:36:59.989608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd8dae16435'
down_revision = 'd2e5f8a1b4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrence_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('recurrence_type', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('weekdays_json', sa.String(length=32), server_default='', nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rollover_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurrence_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurrence_rule_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_rule_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_rule_start_date'), ['start_date'], unique=False)

    op.create_table('task_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurrence_rule_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recurrence_rule_id'], ['recurrence_rule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurrence_rule_id', 'due_date', name='uq_task_occurrence_rule_due_date')
    )
    with op.batch_alter_table('task_occurrence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_occurrence_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_occurrence_discarded_at'), ['discarded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_occurrence_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_occurrence_recurrence_rule_id'), ['recurrence_rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_occurrence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_occurrence_recurrence_rule_id'))
        batch_op.drop_index(batch_op.f('ix_task_occurrence_due_date'))
        batch_op.drop_index(batch_op.f('ix_task_occurrence_discarded_at'))
        batch_op.drop_index(batch_op.f('ix_task_occurrence_completed_at'))

    op.drop_table('task_occurrence')
    with op.batch_alter_table('recurrence_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurrence_rule_start_date'))
        batch_op.drop_index(batch_op.f('ix_recurrence_rule_is_active'))
        batch_op.drop_index(batch_op.f('ix_recurrence_rule_end_date'))

    op.drop_table('recurrence_rule')
    # ### end Alembic commands ###
