"""Add optional task rollover controls

Revision ID: 268a59cac5dd
Revises: 7d8e9f0a1b23
Create Date: 2026-07-31 14:09:18.525700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268a59cac5dd'
down_revision = '7d8e9f0a1b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rollover_enabled', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('rollover_enabled')

    # ### end Alembic commands ###
